# Generated by Django 2.2 on 2019-04-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Category',
            new_name='category',
        ),
    ]
